- type: job
  id: NanotrasenRepresentative
  name: job-name-ntr
  description: job-description-ntr
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 180000  #50 hours
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - CentralCommand
  - Brig
  - Security
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Atmospherics
  - Medical
  - Chemistry
  - Research
  - Cargo
  - Salvage
  - Command
  - NanotrasenRepresentative
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    id: NTRPDA
    ears: ClothingHeadsetAltCommand
    pocket1: UniqueNanorepLockerTeleporter
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation
